node ('ci1') {

    def buildNumber = env.BUILD_NUMBER

    stage 'Stage Checkout'
    git credentialsId: '9a65d10b-144b-4b63-9f93-91f9ef1ce543', url: 'ssh://git@stash.tesseractmobile.net:7999/arduino/efim.git'

    stage 'Stage Build'
    sh "cd PocketBot && chmod +x ./gradlew"
    sh "cd PocketBot && ./gradlew clean assembleDebug"

    stage 'Stage Unit Test'
    sh "cd PocketBot && ./gradlew test"

    stage 'Stage Connected Test'
    sh "cd PocketBot && ./gradlew uninstallAll"
    sh "cd PocketBot && ./gradlew connectedDebugAndroidTest"

    stage 'Stage Beta Release'
    //Update build number
    sh "cd PocketBot && ./gradlew incrementVersion"
    sh "cd PocketBot && git config --global user.email \"jenkins@tesseractmobile.com\""
    sh "cd PocketBot && git config --global user.name \"Jenkins\""
    sh "cd PocketBot && git commit -a -m\"Updated version number from Jenkins build $buildNumber\""
    sh "cd PocketBot && git pull origin master"
    sh "cd PocketBot && git push origin master"
    sh "cd PocketBot && git checkout beta"
    sh "cd PocketBot && git merge origin/master"
    sh "cd PocketBot && git push origin beta"
    //Upload to Crashlytics beta
    sh "cd PocketBot && ./gradlew assembleDebug crashlyticsUploadDistributionDebug"
}